modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Vazkii/Morph-o-Tool"
license="Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License"

[[mods]]
modId="morphtool"
displayName="Morph-o-Tool"
version="${file.jarVersion}"
authors="Vazkii, MoreThanHidden"
description='''
The wrench to end all wrenches.
'''
[[dependencies.morphtool]]
    modId="autoreglib"
    mandatory=true
    versionRange="[1.7-52,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.morphtool]]
    modId="forge"
    mandatory=true
    versionRange="[38.0.17,)"
    ordering="AFTER"
    side="BOTH"
